import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar, {
  NavigationItem,
  NavigationList,
} from "@/components/Navigation/Navigation";
import { SearchContainer } from "@/components/Search/Search";
import SearchInput from "@/components/Search/Search";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-screen p-8 pb-20 sm:p-20">
          <div className="max-w-[680px] mx-auto">
            <NavBar className="w-full mb-12 flex justify-between items-center">
              <NavigationList>
                <NavigationItem>Experiments</NavigationItem>
                <NavigationItem active={true}>Notes</NavigationItem>
                <NavigationItem>Projects</NavigationItem>
                <NavigationItem>About</NavigationItem>
              </NavigationList>
              <SearchContainer>
                <SearchInput />
              </SearchContainer>
            </NavBar>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
